put http://127.0.0.1:3000/films?id=3 http/1.1
content-type: application/json

{
  "title": "Cirno's revenge",
  "source": "2hou 12.8",
  "description": "Cirno is mad at Okina",
  "thumb": "Okina breaking Cirno's neck"
}